---
title: "Mapping Problem"
author: "David Kane"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(sf)
library(tidyverse)
```

The purpose of this document is to highlight a mapping problem that is making me crazy. With luck, you can help! I am using data from the [Stanford Open Policing Project](https://openpolicing.stanford.edu/). Toward [the middle of this page](https://openpolicing.stanford.edu/data/) is the data for Hartford.

```{r}
# Need two data sets. An RDS file with the traffic stops information and a shape
# file for the city of Hartford.

orig <- read_rds(url("https://stacks.stanford.edu/file/druid:tr137st9964/tr137st9964_ct_hartford_2019_02_25.rds")) 

# read_sf() is an alias, but it is a good alias.

shapes <- read_sf(url("https://stacks.stanford.edu/file/druid:tr137st9964/tr137st9964_ct_hartford_shapefiles_2019_02_25.tgz"))

# It is now easy to make a simple map of Hartford.

ggplot(data = shapes) + 
  geom_sf()

```

```{r, eval=FALSE}
# points <- orig %>% sample_n(10)
# 
# ggplot(data = shapes) + 
#   geom_sf() +
#   geom_point(data = points, aes(y = lat, x = lng)) 
  # coord_sf(xlim = c(-72.7, -72.6), ylim = c(41.7, 41.85), expand = FALSE)
```




